//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle
    {
        public int Numero { get; set; }
        public int ID_Orden { get; set; }
        public int ID_Parte { get; set; }
        public int ID_Proveedor { get; set; }
        public decimal Precio { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Orden Orden { get; set; }
        public virtual Parte Parte { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
